env: dev
app:
  application: 'hancock:ms-dlt-adapter'
  hostname: 'localhost'
  server:
    protocol: 'http'
    host: 'localhost'
    port: 3000
    externalPort: 3000
    base: ''
    externalBase: ''
  blockchain:
    ethereum:
      protocol: http
      host: ganache
      port: 8545
  db:
    protocol: mongodb
    hosts: mongo:27017
    database: 'hancock'
    params: ''
    user: ''
    pass: ''
    ethereum:
      database: hancock
      collections:
        contractAbis: sc_abi
        contractInstances: sc_instance
        tokenInstances: sc_token
  logger:
    logLevel: debug
  protocol: 'hancock://qr?code=__CODE__'  